import { type NextPage } from "next";
import Head from "next/head";
import Textarea from "../components/Textarea";
import Select from "../components/Select";
import Button from "../components/Button";
import { useState } from "react";
import { Data } from "./api/generate";

export type ArtStyle = {
  id: number;
  name: string;
};

const artStyles: ArtStyle[] = [
  {
    id: 1,
    name: "Cyberpunk",
  },
  {
    id: 2,
    name: "8-bit",
  },
  {
    id: 3,
    name: "Photorealism",
  },
  {
    id: 4,
    name: "Monet",
  },
  {
    id: 5,
    name: "Rembrandt",
  },
];

const Home: NextPage = () => {
  const [description, setDescription] = useState("");
  const [selected, setSelected] = useState(artStyles[3]);
  const [image, setImage] = useState("");
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-6">
        <h1 className="text-3xl font-bold">AI Pet Portrait Generator</h1>
        <Textarea value={description} setValue={setDescription} />
        <Select
          selected={selected}
          setSelected={setSelected}
          artStyles={artStyles}
        />
        <div className="w-1/2">
          <Button
            onClick={() => {
              generatePet();
            }}
          />
        </div>
        {image ? (
          <div>
            <img src={image} />
          </div>
        ) : null}
      </main>
    </>
  );

  async function generatePet() {
    const response = await fetch("/api/generate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        description,
        artStyle: selected?.name,
      }),
    });

    const data: Data = await response.json();

    setImage(data.data);
  }
};

export default Home;
